FROM psbds/dev-container-aks:v1.1.3


RUN echo 'source /workspaces/$(ls /workspaces)/cli/autocomplete.bash' >> ~/.bashrc
RUN echo 'alias akssnippets=/workspaces/$(ls /workspaces)/cli/index.bash' >> ~/.bashrc